### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by Akxe**

### CODE REVIEW

**Comment by codehippie1** [comment]
Let me test this first

**Comment by Akxe** [comment]
Just rebased. This fixes the `createObjectURL` memory leak using `revokeObjectURL`.

[MDN Example](https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#example_using_object_urls_to_display_images)

**Comment by codehippie1** [comment]
@Akxe, You are super quick. Appreciate it. Merging

**Comment by provegard** [comment]
Looks like there is still a leak when the component is destroyed, right?

**Comment by Akxe** [comment]
This PR fixed one. Did you find any other?

**Comment by provegard** [comment]
I just noticed that the added `relaseUrl` function is not called in `ngOnDestroy` (which doesn't exist), so when the component is destroyed, the last object URL isn't revoked.

**Comment by Akxe** [comment]
Well... It must have gotten removed when rebasing the PR on the new master... 

I am out of the office. Would you create the mentioned fix?

**Pull request merged**
