### PR TITLE
feat: upgrade Angular 18

### PR DESCRIPTION
**Pull request by nicorivat**
Hi,

I updated the library and the SampleApp to Angular 18 :)

Feel free to tell me if there is something else I should do / update !

### CODE REVIEW

**Comment by codehippie1** [comment]
@nicorivat Thanks, buddy. The diff looks good to me. Merging

**Comment by nicorivat** [comment]
@codehippie1 Thanks for the merge ;)

Do you think you we will be able to create a release soon ?

**Comment by codehippie1** [comment]
Sure. I will do that today or tomorrow

**Comment by nicorivat** [comment]
@codehippie1 Any news about the release ? :)

**Comment by codehippie1** [comment]
@nicorivat Published 18.0 just now. Thanks for the reminder.

**Pull request merged**
